package defalt.featureOperation.di

import defalt.featureOperation.usecase.featureOperationUseCaseModule
import defalt.featureOperation.viewModel.featureOperationViewModelModule


val operationModule = listOf(featureOperationUseCaseModule, featureOperationViewModelModule)
