/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.core.api.offer.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param code 
 * @param message 
 * @param details 
 */
@Serializable

data class Error (

    @SerialName(value = "code")
    val code: kotlin.String? = null,

    @SerialName(value = "message")
    val message: kotlin.String? = null,

    @SerialName(value = "details")
    val details: kotlin.String? = null

) {


}

