/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.core.api.offer.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param title
 * @param description
 * @param state
 * @param startDate
 * @param endDate
 * @param picturePath
 */
@Serializable
data class OffersPostRequest(

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String,

    @SerialName(value = "state")
    val state: OffersPostRequest.State,

    @Contextual @SerialName(value = "start_date")
    val startDate: java.time.LocalDate,

    @Contextual @SerialName(value = "end_date")
    val endDate: java.time.LocalDate,

    @SerialName(value = "picturePath")
    val picturePath: kotlin.String? = null,

) {

    /**
     *
     *
     * Values: ACTIVE,INACTIVE,EXPIRED
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "active")
        ACTIVE("active"),

        @SerialName(value = "inactive")
        INACTIVE("inactive"),

        @SerialName(value = "expired")
        EXPIRED("expired"),
    }
}
