/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.core.api.offer.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param picturePath 
 * @param title 
 * @param description 
 * @param state 
 * @param startDate 
 * @param endDate 
 */
@Serializable

data class OffersIdPutRequest (

    @SerialName(value = "picturePath")
    val picturePath: kotlin.String? = null,

    @SerialName(value = "title")
    val title: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "state")
    val state: OffersIdPutRequest.State? = null,

    @Contextual @SerialName(value = "start_date")
    val startDate: java.time.LocalDate? = null,

    @Contextual @SerialName(value = "end_date")
    val endDate: java.time.LocalDate? = null

) {

    /**
     * 
     *
     * Values: ACTIVE,INACTIVE,EXPIRED
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "active") ACTIVE("active"),
        @SerialName(value = "inactive") INACTIVE("inactive"),
        @SerialName(value = "expired") EXPIRED("expired");
    }

}

