/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.core.api.offer.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param state 
 */
@Serializable

data class OffersIdStatePatchRequest (

    @SerialName(value = "state")
    val state: OffersIdStatePatchRequest.State

) {

    /**
     * 
     *
     * Values: ACTIVE,INACTIVE,EXPIRED
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "active") ACTIVE("active"),
        @SerialName(value = "inactive") INACTIVE("inactive"),
        @SerialName(value = "expired") EXPIRED("expired");
    }

}

