/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.core.api.offer.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param id Identifiant de l'offre
 * @param title Titre de l'offre
 * @param description Description détaillée de l'offre
 * @param state État de l'offre
 * @param startDate Date de début de l'offre
 * @param endDate Date de fin de l'offre
 * @param picturePath Chemin vers l'image de l'offre
 */
@Serializable
data class Offer(

    // Identifiant de l'offre
    @SerialName(value = "id")
    val id: kotlin.Int,

    // Titre de l'offre
    @SerialName(value = "title")
    val title: kotlin.String,

    // Description détaillée de l'offre
    @SerialName(value = "description")
    val description: kotlin.String,

    // État de l'offre
    @SerialName(value = "state")
    val state: Offer.State,

    // Date de début de l'offre
    @Contextual @SerialName(value = "start_date")
    val startDate: java.time.LocalDate,

    // Date de fin de l'offre
    @Contextual @SerialName(value = "end_date")
    val endDate: java.time.LocalDate,

    // Chemin vers l'image de l'offre
    @SerialName(value = "picturePath")
    val picturePath: kotlin.String? = null,

) {

    /**
     * État de l'offre
     *
     * Values: ACTIVE,INACTIVE,EXPIRED
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "active")
        ACTIVE("active"),

        @SerialName(value = "inactive")
        INACTIVE("inactive"),

        @SerialName(value = "expired")
        EXPIRED("expired"),
    }
}
