/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.core.api.operation.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param ibanTarget
 * @param name
 */
@Serializable
data class BeneficiariesPostRequest(

    @SerialName(value = "iban_target")
    val ibanTarget: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

)
