/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.core.api.operation.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param state
 */
@Serializable
data class OperationsIdStatePatchRequest(

    @SerialName(value = "state")
    val state: OperationsIdStatePatchRequest.State,

) {

    /**
     *
     *
     * Values: PENDING,COMPLETED,FAILED,CANCELLED
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "pending")
        PENDING("pending"),

        @SerialName(value = "completed")
        COMPLETED("completed"),

        @SerialName(value = "failed")
        FAILED("failed"),

        @SerialName(value = "cancelled")
        CANCELLED("cancelled"),
    }
}
