/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.core.api.operation.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param reason Raison de l'annulation
 */
@Serializable
data class OperationsIdCancelPostRequest(

    // Raison de l'annulation
    @SerialName(value = "reason")
    val reason: kotlin.String? = null,

)
