/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.core.api.operation.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param originalOperation
 * @param cancellationOperation
 */
@Serializable
data class OperationsIdCancelPost201Response(

    @SerialName(value = "original_operation")
    val originalOperation: Operation? = null,

    @SerialName(value = "cancellation_operation")
    val cancellationOperation: Operation? = null,

)
