/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.core.api.operation.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param bankAccountSourceId ID du compte bancaire source
 * @param label Libellé de l'opération
 * @param ibanTarget IBAN du compte destinataire
 * @param amount Montant de l'opération (positif)
 */
@Serializable
data class OperationsPostRequest(

    // ID du compte bancaire source
    @SerialName(value = "bank_account_source_id")
    val bankAccountSourceId: kotlin.Int,

    // Libellé de l'opération
    @SerialName(value = "label")
    val label: kotlin.String,

    // IBAN du compte destinataire
    @SerialName(value = "iban_target")
    val ibanTarget: kotlin.String,

    // Montant de l'opération (positif)
    @SerialName(value = "amount")
    val amount: kotlin.Double,

)
