/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.network.api.bank.model

import defalt.network.api.bank.model.State

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param overdraftLimit 
 * @param state 
 */
@Serializable

data class BankAccountParameter (

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "overdraft_limit")
    val overdraftLimit: kotlin.Double? = null,

    @Contextual @SerialName(value = "state")
    val state: State? = null

) {


}

