/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.network.api.bank.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Version simple (pour listes)
 *
 * @param id
 * @param parameterId
 * @param typeId
 * @param sold
 * @param iban
 */
@Serializable
data class BankAccount(

    @SerialName(value = "id")
    val id: kotlin.String? = null,

    @SerialName(value = "parameter_id")
    val parameterId: kotlin.Int? = null,

    @SerialName(value = "type_id")
    val typeId: kotlin.Int? = null,

    @SerialName(value = "sold")
    val sold: kotlin.Double? = null,

    @SerialName(value = "iban")
    val iban: kotlin.String? = null,

)
