/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.network.api.bank.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param typeId
 * @param iban
 * @param sold
 * @param overdraftLimit
 * @param state
 */
@Serializable
data class BankAccountCreateRequest(

    @SerialName(value = "type_id")
    val typeId: kotlin.Int,

    @SerialName(value = "iban")
    val iban: kotlin.String,

    @SerialName(value = "sold")
    val sold: kotlin.Double,

    @SerialName(value = "overdraft_limit")
    val overdraftLimit: kotlin.Double,

    @Contextual @SerialName(value = "state")
    val state: State? = null,

)
