/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.network.api.bank.model

import defalt.network.api.bank.model.BankAccountParameter
import defalt.network.api.bank.model.Type

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Version complète (avec détails)
 *
 * @param id 
 * @param parameter 
 * @param type 
 * @param sold 
 * @param iban 
 */
@Serializable

data class BankAccountDetail (

    @SerialName(value = "id")
    val id: kotlin.String? = null,

    @SerialName(value = "parameter")
    val parameter: BankAccountParameter? = null,

    @SerialName(value = "type")
    val type: Type? = null,

    @SerialName(value = "sold")
    val sold: kotlin.Double? = null,

    @SerialName(value = "iban")
    val iban: kotlin.String? = null

) {


}

