/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.network.api.bank.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Lien compte-utilisateur (co-titulaire)
 *
 * @param bankAccountId 
 * @param accountId 
 */
@Serializable

data class BankAccountPivot (

    @SerialName(value = "bank_account_id")
    val bankAccountId: kotlin.String,

    @SerialName(value = "account_id")
    val accountId: kotlin.String

) {


}

