/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.network.api.bank.model

import defalt.network.api.bank.model.State

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param typeId Type de compte existant
 * @param iban IBAN unique du compte
 * @param sold Solde initial
 * @param overdraftLimit Découvert autorisé
 * @param state 
 */
@Serializable

data class BankAccountCreateRequest (

    /* Type de compte existant */
    @SerialName(value = "type_id")
    val typeId: kotlin.Int,

    /* IBAN unique du compte */
    @SerialName(value = "iban")
    val iban: kotlin.String,

    /* Solde initial */
    @SerialName(value = "sold")
    val sold: kotlin.Double,

    /* Découvert autorisé */
    @SerialName(value = "overdraft_limit")
    val overdraftLimit: kotlin.Double,

    @Contextual @SerialName(value = "state")
    val state: State? = null

) {


}

