/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.network.api.bank.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * Values: ACTIVE,INACTIVE,BLOQUED,CLOSED
 */
@Serializable
enum class State(val value: kotlin.String) {

    @SerialName(value = "ACTIVE")
    ACTIVE("ACTIVE"),

    @SerialName(value = "INACTIVE")
    INACTIVE("INACTIVE"),

    @SerialName(value = "BLOQUED")
    BLOQUED("BLOQUED"),

    @SerialName(value = "CLOSED")
    CLOSED("CLOSED"),
    ;

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is State) "$data" else null

        /**
         * Returns a valid [State] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): State? = data?.let {
            val normalizedData = "$it".lowercase()
            values().firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}
