/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.network.api.bank.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param id
 * @param name
 */
@Serializable
data class Type(

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

)
