openapi: 3.0.0
info:
  title: Account API
  description: API de gestion des comptes, rôles et informations personnelles
  version: 1.1.0
servers:
  - url: http://localhost:8081/api/v1
    description: Serveur de gestion des comptes

paths:

  /roles:
    get:
      summary: Liste tous les rôles (Admin uniquement)
      tags: [Role]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Liste récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
        '401':
          description: Non autorisé (Token manquant ou invalide)
        '403':
          description: Interdit (Permission insuffisante)

  /roles/{id}:
    get:
      summary: Récupérer un rôle par son ID
      tags: [Role]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Rôle trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '404':
          description: Rôle non trouvé

  /personalInformation:
    get:
      summary: Liste toutes les informations personnelles (Admin uniquement)
      tags: [PersonalInformation]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonalInformation'
        '401':
          description: Non autorisé
        '403':
          description: Interdit
    post:
      summary: Créer une fiche d'information personnelle
      tags: [PersonalInformation]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonalInformationRegister'
      responses:
        '201':
          description: Créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalInformation'

  /personalInformation/{id}:
    get:
      summary: Récupérer une info personnelle par ID
      tags: [PersonalInformation]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalInformation'
        '404':
          description: Non trouvé

  /accounts:
    get:
      summary: Liste tous les comptes (Admin uniquement)
      tags: [Account]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '401':
          description: Non autorisé
        '403':
          description: Interdit
    post:
      summary: Créer un nouveau compte
      description: Crée le compte, le rôle et les informations personnelles liées.
      tags: [Account]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRegister'
      responses:
        '201':
          description: Compte créé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'

  /accounts/{id}:
    get:
      summary: Récupérer un compte par ID
      tags: [Account]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Compte trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Compte non trouvé
    delete:
      summary: Supprimer un compte (Admin uniquement)
      tags: [Account]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Compte supprimé avec succès (retourne true)
          content:
            application/json:
              schema:
                type: boolean
        '404':
          description: Compte non trouvé
        '401':
          description: Non autorisé
        '403':
          description: Interdit

  /accounts/activate/{id}:
    put:
      summary: Activer un compte (Admin uniquement)
      tags: [Account]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Compte activé avec succès
          content:
            application/json:
              schema:
                type: boolean
        '404':
          description: Compte non trouvé
        '401':
          description: Non autorisé
        '403':
          description: Interdit

  /accounts/deactivate/{id}:
    put:
      summary: Désactiver un compte (Admin uniquement)
      tags: [Account]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Compte désactivé avec succès
          content:
            application/json:
              schema:
                type: boolean
        '404':
          description: Compte non trouvé
        '401':
          description: Non autorisé
        '403':
          description: Interdit

  /accounts/role/{id}:
    get:
      summary: Récupérer le rôle associé à un compte
      tags: [Account]
      parameters:
        - name: id
          in: path
          description: ID du compte
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Rôle trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '404':
          description: Compte ou Rôle non trouvé

  /accounts/personalInformation/{id}:
    get:
      summary: Récupérer les informations personnelles associées à un compte
      tags: [Account]
      parameters:
        - name: id
          in: path
          description: ID du compte
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Infos trouvées
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalInformation'
        '404':
          description: Compte ou Infos non trouvées

  /accounts/signin:
    post:
      summary: Connexion utilisateur
      tags: [Account]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
      responses:
        '200':
          description: Connexion réussie, retourne le token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRequest'
        '404':
          description: Compte non trouvé
        '401':
          description: Mot de passe incorrect

  /accounts/validate:
    post:
      summary: Valider un token JWT
      tags: [Account]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
      responses:
        '200':
          description: Token valide
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: Token invalide ou expiré

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RoleEnum:
      type: string
      enum:
        - ADMIN
        - CUSTOMER

    Role:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    PersonalInformation:
      type: object
      properties:
        id:
          type: integer
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
          format: email
        address:
          type: string
        phone_number:
          type: string

    PersonalInformationRegister:
      type: object
      required:
        - firstname
        - lastname
        - email
      properties:
        firstname:
          type: string
          exemple: "John"
        lastname:
          type: string
          exemple: "Doe"
        email:
          type: string
          exemple: "john.doe@localhost.com"
          format: email
        address:
          type: string
          exemple: "123 Main St, Anytown"
        phone_number:
          type: string
          exemple: "0123456789"

    Account:
      type: object
      properties:
        id:
          type: string
        personal_info_id:
          type: integer
          description: ID faisant référence à PersonalInformation
        role_id:
          type: integer
          description: ID faisant référence à Role
        state:
          type: string

    AccountRegister:
      type: object
      required:
        - personal_info
        - role_id
        - password
      properties:
        personal_info:
          $ref: '#/components/schemas/PersonalInformationRegister'
        role_id:
          type: integer
          exemple: 1
          description: "ID du rôle existant (ex: 1 pour Admin, 2 pour User)"
        password:
          type: string
          exemple: "123456789"
          format: password
          writeOnly: true
        state:
          type: string

    SignInRequest:
      type: object
      required:
        - id
        - password
      properties:
        id:
          type: string
          example: "123456789123"
        password:
          type: string
          format: password
          example: "123456789"

    TokenRequest:
      type: object
      required:
        - jwt
      properties:
        jwt:
          type: string
          description: "Token JWT"
          example: "eyJhbGciOiJIUzI1NiJ9..."

    TokenResponse:
      type: object
      description: "Données utilisateur extraites et décodées depuis le token JWT"
      properties:
        id:
          type: string
          description: "Identifiant unique de l'utilisateur (Subject du token)"
          example: "123456789123"
        role:
          type: string
          description: "Rôle de l'utilisateur"
          example: "ADMIN"