/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.network.api.account.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param personalInfo
 * @param role
 * @param password
 */
@Serializable
data class AccountRegister(

    @SerialName(value = "personal_info")
    val personalInfo: PersonalInformationRegister,

    @Contextual @SerialName(value = "role")
    val role: RoleEnum,

    @SerialName(value = "password")
    val password: kotlin.String,

)
