/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.network.api.account.model

import defalt.network.api.account.model.PersonalInformationRegister

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param personalInfo 
 * @param roleId ID du rôle existant (ex: 1 pour Admin, 2 pour User)
 * @param password 
 */
@Serializable

data class AccountRegister (

    @SerialName(value = "personal_info")
    val personalInfo: PersonalInformationRegister,

    /* ID du rôle existant (ex: 1 pour Admin, 2 pour User) */
    @SerialName(value = "role_id")
    val roleId: kotlin.Int,

    @SerialName(value = "password")
    val password: kotlin.String

) {


}

