/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.network.api.account.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Données utilisateur extraites et décodées depuis le token JWT
 *
 * @param id Identifiant unique de l'utilisateur (Subject du token)
 * @param role Rôle de l'utilisateur
 */
@Serializable

data class TokenResponse (

    /* Identifiant unique de l'utilisateur (Subject du token) */
    @SerialName(value = "id")
    val id: kotlin.String? = null,

    /* Rôle de l'utilisateur */
    @SerialName(value = "role")
    val role: kotlin.String? = null

) {


}

