/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.core.api.bank.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param typeId
 * @param sold
 */
@Serializable
data class BankAccountsIdPutRequest(

    @SerialName(value = "type_id")
    val typeId: kotlin.Int? = null,

    @SerialName(value = "sold")
    val sold: kotlin.Double? = null,

)
