/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.core.api.bank.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param state 
 */
@Serializable

data class BankAccountsIdStatePatchRequest (

    @SerialName(value = "state")
    val state: BankAccountsIdStatePatchRequest.State

) {

    /**
     * 
     *
     * Values: ACTIVE,INACTIVE,BLOQUED,CLOSED
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "active") ACTIVE("active"),
        @SerialName(value = "inactive") INACTIVE("inactive"),
        @SerialName(value = "bloqued") BLOQUED("bloqued"),
        @SerialName(value = "closed") CLOSED("closed");
    }

}

