/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.core.api.bank.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param parameterId
 * @param typeId
 * @param sold
 * @param iban
 * @param accountId ID du compte utilisateur à lier
 */
@Serializable
data class BankAccountsPostRequest(

    @SerialName(value = "parameter_id")
    val parameterId: kotlin.Int,

    @SerialName(value = "type_id")
    val typeId: kotlin.Int,

    @SerialName(value = "sold")
    val sold: kotlin.Double,

    @SerialName(value = "iban")
    val iban: kotlin.String,

    // ID du compte utilisateur à lier
    @SerialName(value = "account_id")
    val accountId: kotlin.Int,

)
