/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.core.api.bank.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Identifiant des paramètres
 * @param overdraftLimit Limite de découvert autorisé
 * @param state État des paramètres
 */
@Serializable

data class BankAccountParameter (

    /* Identifiant des paramètres */
    @SerialName(value = "id")
    val id: kotlin.Int,

    /* Limite de découvert autorisé */
    @SerialName(value = "overdraft_limit")
    val overdraftLimit: kotlin.Double,

    /* État des paramètres */
    @SerialName(value = "state")
    val state: BankAccountParameter.State

) {

    /**
     * État des paramètres
     *
     * Values: ACTIVE,INACTIVE
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "active") ACTIVE("active"),
        @SerialName(value = "inactive") INACTIVE("inactive");
    }

}

