/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.core.api.bank.model

import defalt.core.api.bank.model.BankAccountParameter
import defalt.core.api.bank.model.Type

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Numéro de compte bancaire
 * @param parameterId ID des paramètres du compte
 * @param typeId ID du type de compte
 * @param sold Solde du compte
 * @param iban IBAN du compte
 * @param parameter 
 * @param type 
 */
@Serializable

data class BankAccountDetails (

    /* Numéro de compte bancaire */
    @SerialName(value = "id")
    val id: kotlin.Int,

    /* ID des paramètres du compte */
    @SerialName(value = "parameter_id")
    val parameterId: kotlin.Int,

    /* ID du type de compte */
    @SerialName(value = "type_id")
    val typeId: kotlin.Int,

    /* Solde du compte */
    @SerialName(value = "sold")
    val sold: kotlin.Double,

    /* IBAN du compte */
    @SerialName(value = "iban")
    val iban: kotlin.String,

    @SerialName(value = "parameter")
    val parameter: BankAccountParameter? = null,

    @SerialName(value = "type")
    val type: Type? = null

) {


}

