/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.core.api.bank.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param overdraftLimit 
 * @param state 
 */
@Serializable

data class ParametersPostRequest (

    @SerialName(value = "overdraft_limit")
    val overdraftLimit: kotlin.Double,

    @SerialName(value = "state")
    val state: ParametersPostRequest.State

) {

    /**
     * 
     *
     * Values: ACTIVE,INACTIVE
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "active") ACTIVE("active"),
        @SerialName(value = "inactive") INACTIVE("inactive");
    }

}

