/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.core.api.bank.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param overdraftLimit
 * @param state
 */
@Serializable
data class ParametersIdPutRequest(

    @SerialName(value = "overdraft_limit")
    val overdraftLimit: kotlin.Double? = null,

    @SerialName(value = "state")
    val state: ParametersIdPutRequest.State? = null,

) {

    /**
     *
     *
     * Values: ACTIVE,INACTIVE
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "active")
        ACTIVE("active"),

        @SerialName(value = "inactive")
        INACTIVE("inactive"),
    }
}
