/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.core.api.bank.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Identifiant du type
 * @param name Nom du type
 */
@Serializable

data class Type (

    /* Identifiant du type */
    @SerialName(value = "id")
    val id: kotlin.Int,

    /* Nom du type */
    @SerialName(value = "name")
    val name: kotlin.String

) {


}

