openapi: 3.0.3
info:
  title: Bank API
  description: API pour la gestion des comptes bancaires, types et paramètres
  version: 1.0.0

servers:
  - url: http://localhost:8081/api/v1
    description: Serveur de Bank API

tags:
  - name: BankAccount
  - name: Type
  - name: BankAccountParameter
  - name: BankAccountPivot

paths:
  /bank-accounts:
    get:
      tags: [BankAccount]
      summary: Récupérer la liste des comptes bancaires
      security:
        - bearerAuth: []
      parameters:
        - name: account_id
          in: query
          schema:
            type: integer
        - name: type_id
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Liste récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BankAccount'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    post:
      tags: [BankAccount]
      summary: Créer un nouveau compte bancaire
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankAccount'
      responses:
        '201':
          description: Compte bancaire créé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccount'

  /bank-accounts/{id}:
    get:
      tags: [BankAccount]
      summary: Récupérer un compte bancaire
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Compte trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccount'
        '404':
          $ref: '#/components/responses/NotFoundError'

    put:
      tags: [BankAccount]
      summary: Mettre à jour un compte bancaire
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankAccount'
      responses:
        '200':
          description: Compte mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccount'

    delete:
      tags: [BankAccount]
      summary: Supprimer un compte bancaire
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Compte supprimé

  /bank-accounts/{id}/state:
    patch:
      tags: [BankAccount]
      summary: Changer l'état d'un compte bancaire
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [state]
              properties:
                state:
                  $ref: '#/components/schemas/State'
      responses:
        '200':
          description: État modifié
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccount'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'

  /bank-accounts/{id}/balance:
    get:
      tags: [BankAccount]
      summary: Récupérer le solde d'un compte bancaire
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Solde récupéré
          content:
            application/json:
              schema:
                type: object
                properties:
                  sold:
                    type: number
                    format: double
        '404':
          $ref: '#/components/responses/NotFoundError'

  /types:
    get:
      tags: [Type]
      summary: Récupérer la liste des types
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Type'

    post:
      tags: [Type]
      summary: Créer un type
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Type'
      responses:
        '201':
          description: Créé

  /parameters:
    get:
      tags: [BankAccountParameter]
      summary: Récupérer les paramètres
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BankAccountParameter'

    post:
      tags: [BankAccountParameter]
      summary: Créer des paramètres
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankAccountParameter'
      responses:
        '201':
          description: Créé

  # ============== BankAccountPivot Endpoints ==============

  /bank-accounts/{bankAccountId}/link/{accountId}:
    post:
      tags: [BankAccountPivot]
      summary: Lier un compte (Account) à un compte bancaire (BankAccount)
      description: Crée une relation many-to-many entre un Account et un BankAccount
      security:
        - bearerAuth: []
      parameters:
        - name: bankAccountId
          in: path
          required: true
          schema:
            type: string
          description: ID du compte bancaire
        - name: accountId
          in: path
          required: true
          schema:
            type: integer
          description: ID du compte utilisateur
      responses:
        '201':
          description: Lien créé avec succès
        '404':
          $ref: '#/components/responses/NotFoundError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /bank-accounts/{bankAccountId}/unlink/{accountId}:
    delete:
      tags: [BankAccountPivot]
      summary: Délier un compte d'un compte bancaire
      description: Supprime la relation entre un Account et un BankAccount
      security:
        - bearerAuth: []
      parameters:
        - name: bankAccountId
          in: path
          required: true
          schema:
            type: string
        - name: accountId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Lien supprimé avec succès
        '404':
          $ref: '#/components/responses/NotFoundError'

  /bank-accounts/{bankAccountId}/unlink-all:
    delete:
      tags: [BankAccountPivot]
      summary: Délier tous les comptes d'un compte bancaire
      description: Supprime toutes les relations d'un BankAccount avec tous les Accounts
      security:
        - bearerAuth: []
      parameters:
        - name: bankAccountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Tous les liens supprimés
        '404':
          $ref: '#/components/responses/NotFoundError'

  /accounts/{accountId}/unlink-all:
    delete:
      tags: [BankAccountPivot]
      summary: Délier tous les comptes bancaires d'un compte
      description: Supprime toutes les relations d'un Account avec tous les BankAccounts
      security:
        - bearerAuth: []
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Tous les liens supprimés
        '404':
          $ref: '#/components/responses/NotFoundError'

  /bank-accounts/{bankAccountId}/accounts:
    get:
      tags: [BankAccountPivot]
      summary: Récupérer tous les comptes liés à un compte bancaire
      description: Liste tous les Account IDs associés à un BankAccount
      security:
        - bearerAuth: []
      parameters:
        - name: bankAccountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Liste des IDs de comptes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
        '404':
          $ref: '#/components/responses/NotFoundError'

  /accounts/{accountId}/bank-accounts:
    get:
      tags: [BankAccountPivot]
      summary: Récupérer tous les comptes bancaires liés à un compte
      description: Liste tous les BankAccount IDs associés à un Account
      security:
        - bearerAuth: []
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Liste des IDs de comptes bancaires
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '404':
          $ref: '#/components/responses/NotFoundError'

components:
  schemas:
    BankAccount:
      type: object
      properties:
        id:
          type: string
        parameter_id:
          type: integer
        type_id:
          type: integer
        sold:
          type: number
          format: double
        iban:
          type: string

    Type:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    BankAccountParameter:
      type: object
      properties:
        id:
          type: integer
        overdraft_limit:
          type: number
          format: double
        state:
          $ref: '#/components/schemas/State'

    State:
      type: string
      description: État possible d'un compte bancaire
      enum:
        - active
        - inactive
        - bloqued
        - closed
      example: active

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: string

  responses:
    UnauthorizedError:
      description: Non autorisé
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFoundError:
      description: Ressource non trouvée
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    BadRequestError:
      description: Requête invalide
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []