/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.network.api.operation.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param accountSourceId ID du compte source
 * @param ibanTarget IBAN du bénéficiaire
 * @param name Nom du bénéficiaire
 * @param id Identifiant du bénéficiaire
 */
@Serializable
data class Beneficiary(

    // ID du compte source
    @SerialName(value = "account_source_id")
    val accountSourceId: kotlin.String,

    // IBAN du bénéficiaire
    @SerialName(value = "iban_target")
    val ibanTarget: kotlin.String,

    // Nom du bénéficiaire
    @SerialName(value = "name")
    val name: kotlin.String,

    // Identifiant du bénéficiaire
    @SerialName(value = "id")
    val id: kotlin.Int? = null,

)
