/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.network.api.operation.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * État de l'opération
 *
 * Values: PENDING,COMPLETED,FAILED,CANCELLED
 */
@Serializable
enum class OperationState(val value: kotlin.String) {

    @SerialName(value = "pending")
    PENDING("pending"),

    @SerialName(value = "completed")
    COMPLETED("completed"),

    @SerialName(value = "failed")
    FAILED("failed"),

    @SerialName(value = "cancelled")
    CANCELLED("cancelled"),
    ;

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is OperationState) "$data" else null

        /**
         * Returns a valid [OperationState] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OperationState? = data?.let {
            val normalizedData = "$it".lowercase()
            values().firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}
