/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.network.api.operation.model

import defalt.network.api.operation.model.OperationState

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Critères de filtrage pour la liste des opérations
 *
 * @param state 
 * @param dateFrom Date de début (incluse)
 * @param dateTo Date de fin (incluse)
 */
@Serializable

data class OperationFilter (

    @Contextual @SerialName(value = "state")
    val state: OperationState? = null,

    /* Date de début (incluse) */
    @Contextual @SerialName(value = "date_from")
    val dateFrom: java.time.OffsetDateTime? = null,

    /* Date de fin (incluse) */
    @Contextual @SerialName(value = "date_to")
    val dateTo: java.time.OffsetDateTime? = null

) {


}

