/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.core.api.account.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param username
 * @param password
 * @param nom
 * @param prenom
 * @param email
 * @param id
 */
@Serializable
data class Account(

    @SerialName(value = "username")
    val username: String,

    @SerialName(value = "password")
    val password: String,

    @SerialName(value = "nom")
    val nom: String,

    @SerialName(value = "prenom")
    val prenom: String,

    @SerialName(value = "email")
    val email: String,

    @SerialName(value = "id")
    val id: Int? = null,

)
