/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.core.api.account.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param personalInfo
 * @param roleId ID du rôle existant (ex: 1 pour Admin, 2 pour User)
 * @param password
 * @param state
 */
@Serializable
data class AccountRegister(

    @SerialName(value = "personal_info")
    val personalInfo: PersonalInformationRegister,

    // ID du rôle existant (ex: 1 pour Admin, 2 pour User)
    @SerialName(value = "role_id")
    val roleId: kotlin.Int,

    @SerialName(value = "password")
    val password: kotlin.String,

    @SerialName(value = "state")
    val state: kotlin.String? = null,

)
