/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package defalt.core.api.account.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param id
 * @param personalInfoId ID faisant référence à PersonalInformation
 * @param roleId ID faisant référence à Role
 * @param state
 */
@Serializable
data class Account(

    @SerialName(value = "id")
    val id: kotlin.String? = null,

    // ID faisant référence à PersonalInformation
    @SerialName(value = "personal_info_id")
    val personalInfoId: kotlin.Int? = null,

    // ID faisant référence à Role
    @SerialName(value = "role_id")
    val roleId: kotlin.Int? = null,

    @SerialName(value = "state")
    val state: kotlin.String? = null,

)
