/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.core.api.account.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param firstname 
 * @param lastname 
 * @param email 
 * @param address 
 * @param phoneNumber 
 */
@Serializable

data class PersonalInformation (

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "firstname")
    val firstname: kotlin.String? = null,

    @SerialName(value = "lastname")
    val lastname: kotlin.String? = null,

    @SerialName(value = "email")
    val email: kotlin.String? = null,

    @SerialName(value = "address")
    val address: kotlin.String? = null,

    @SerialName(value = "phone_number")
    val phoneNumber: kotlin.String? = null

) {


}

