/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package defalt.core.api.account.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param idBankAccount 
 * @param password 
 */
@Serializable

data class SignInRequest (

    @SerialName(value = "id_bank_account")
    val idBankAccount: kotlin.String,

    @SerialName(value = "password")
    val password: kotlin.String

) {


}

